// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Category struct {
	ID        int64
	Name      string
	CreatedAt time.Time
}

type Customer struct {
	ID          int64
	FullName    string
	PhoneNumber string
	Email       string
	CreatedAt   time.Time
}

type Menu struct {
	ID         int64
	Name       string
	Price      string
	CategoryID int64
	Status     bool
	CreatedAt  time.Time
}

type Order struct {
	ID         int64
	UserID     int64
	CustomerID int64
	TableID    int64
	Status     string
	TotalPrice string
	CreatedAt  time.Time
}

type OrderItem struct {
	ID        int64
	OrderID   int64
	MenuID    int64
	Quantity  int32
	Price     string
	NoteItem  sql.NullString
	Status    string
	CreatedAt time.Time
}

type Payment struct {
	ID            int64
	OrderID       int64
	Amount        string
	PaymentMethod string
	Status        string
	CreatedAt     time.Time
}

type Table struct {
	ID         int64
	Name       string
	QrText     string
	QrImageUrl string
	Status     string
	CreatedAt  time.Time
}

type User struct {
	ID           int64
	Username     string
	HashPassword string
	FullName     string
	Role         string
	Email        string
	CreatedAt    time.Time
}
