// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateMenu(ctx context.Context, arg CreateMenuParams) (Menu, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateTable(ctx context.Context, arg CreateTableParams) (Table, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id int64) error
	DeleteCustomer(ctx context.Context, id int64) error
	DeleteMenu(ctx context.Context, id int64) error
	DeleteOrder(ctx context.Context, id int64) error
	DeleteOrderItem(ctx context.Context, id int64) error
	DeletePayment(ctx context.Context, id int64) error
	DeleteTable(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetCustomer(ctx context.Context, id int64) (Customer, error)
	GetMenu(ctx context.Context, id int64) (Menu, error)
	GetOrder(ctx context.Context, id int64) (Order, error)
	GetOrderItem(ctx context.Context, id int64) (OrderItem, error)
	GetPayment(ctx context.Context, id int64) (Payment, error)
	GetTable(ctx context.Context, id int64) (Table, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListCategory(ctx context.Context, arg ListCategoryParams) ([]Category, error)
	ListCustomer(ctx context.Context, arg ListCustomerParams) ([]Customer, error)
	ListMenu(ctx context.Context, arg ListMenuParams) ([]Menu, error)
	ListOrder(ctx context.Context, arg ListOrderParams) ([]Order, error)
	ListOrderItem(ctx context.Context, arg ListOrderItemParams) ([]OrderItem, error)
	ListPayment(ctx context.Context, arg ListPaymentParams) ([]Payment, error)
	ListTable(ctx context.Context, arg ListTableParams) ([]Table, error)
	ListUser(ctx context.Context, arg ListUserParams) ([]User, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateMenu(ctx context.Context, arg UpdateMenuParams) (Menu, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
	UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (OrderItem, error)
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error)
	UpdateTable(ctx context.Context, arg UpdateTableParams) (Table, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserWithPassword(ctx context.Context, arg UpdateUserWithPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
