// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: service_order_food.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_order_food_proto protoreflect.FileDescriptor

const file_service_order_food_proto_rawDesc = "" +
	"\n" +
	"\x18service_order_food.proto\x12\x02pb\x1a\x15rpc_create_user.proto\x1a\x14rpc_login_user.proto\x1a\x15rpc_update_user.proto\x1a!rpc_updateonlypassword_user.proto\x1a\x1cgoogle/api/annotations.proto2\x93\x03\n" +
	"\x10OrderFoodService\x12W\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/create_user\x12W\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*2\x0f/v1/update_user\x12x\n" +
	"\x12UpdatePasswordUser\x12\x1d.pb.UpdatePasswordUserRequest\x1a\x1e.pb.UpdatePasswordUserResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*2\x18/v1/update_password_user\x12S\n" +
	"\tLoginUser\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/login_userB%Z#github.com/datmaithanh/orderfood/pbb\x06proto3"

var file_service_order_food_proto_goTypes = []any{
	(*CreateUserRequest)(nil),          // 0: pb.CreateUserRequest
	(*UpdateUserRequest)(nil),          // 1: pb.UpdateUserRequest
	(*UpdatePasswordUserRequest)(nil),  // 2: pb.UpdatePasswordUserRequest
	(*LoginUserRequest)(nil),           // 3: pb.LoginUserRequest
	(*CreateUserResponse)(nil),         // 4: pb.CreateUserResponse
	(*UpdateUserResponse)(nil),         // 5: pb.UpdateUserResponse
	(*UpdatePasswordUserResponse)(nil), // 6: pb.UpdatePasswordUserResponse
	(*LoginUserResponse)(nil),          // 7: pb.LoginUserResponse
}
var file_service_order_food_proto_depIdxs = []int32{
	0, // 0: pb.OrderFoodService.CreateUser:input_type -> pb.CreateUserRequest
	1, // 1: pb.OrderFoodService.UpdateUser:input_type -> pb.UpdateUserRequest
	2, // 2: pb.OrderFoodService.UpdatePasswordUser:input_type -> pb.UpdatePasswordUserRequest
	3, // 3: pb.OrderFoodService.LoginUser:input_type -> pb.LoginUserRequest
	4, // 4: pb.OrderFoodService.CreateUser:output_type -> pb.CreateUserResponse
	5, // 5: pb.OrderFoodService.UpdateUser:output_type -> pb.UpdateUserResponse
	6, // 6: pb.OrderFoodService.UpdatePasswordUser:output_type -> pb.UpdatePasswordUserResponse
	7, // 7: pb.OrderFoodService.LoginUser:output_type -> pb.LoginUserResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_order_food_proto_init() }
func file_service_order_food_proto_init() {
	if File_service_order_food_proto != nil {
		return
	}
	file_rpc_create_user_proto_init()
	file_rpc_login_user_proto_init()
	file_rpc_update_user_proto_init()
	file_rpc_updateonlypassword_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_order_food_proto_rawDesc), len(file_service_order_food_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_order_food_proto_goTypes,
		DependencyIndexes: file_service_order_food_proto_depIdxs,
	}.Build()
	File_service_order_food_proto = out.File
	file_service_order_food_proto_goTypes = nil
	file_service_order_food_proto_depIdxs = nil
}
