// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: service_order_food.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderFoodService_CreateUser_FullMethodName         = "/pb.OrderFoodService/CreateUser"
	OrderFoodService_UpdateUser_FullMethodName         = "/pb.OrderFoodService/UpdateUser"
	OrderFoodService_UpdatePasswordUser_FullMethodName = "/pb.OrderFoodService/UpdatePasswordUser"
	OrderFoodService_LoginUser_FullMethodName          = "/pb.OrderFoodService/LoginUser"
)

// OrderFoodServiceClient is the client API for OrderFoodService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderFoodServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	UpdatePasswordUser(ctx context.Context, in *UpdatePasswordUserRequest, opts ...grpc.CallOption) (*UpdatePasswordUserResponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
}

type orderFoodServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderFoodServiceClient(cc grpc.ClientConnInterface) OrderFoodServiceClient {
	return &orderFoodServiceClient{cc}
}

func (c *orderFoodServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, OrderFoodService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderFoodServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, OrderFoodService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderFoodServiceClient) UpdatePasswordUser(ctx context.Context, in *UpdatePasswordUserRequest, opts ...grpc.CallOption) (*UpdatePasswordUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePasswordUserResponse)
	err := c.cc.Invoke(ctx, OrderFoodService_UpdatePasswordUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderFoodServiceClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, OrderFoodService_LoginUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderFoodServiceServer is the server API for OrderFoodService service.
// All implementations must embed UnimplementedOrderFoodServiceServer
// for forward compatibility.
type OrderFoodServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	UpdatePasswordUser(context.Context, *UpdatePasswordUserRequest) (*UpdatePasswordUserResponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	mustEmbedUnimplementedOrderFoodServiceServer()
}

// UnimplementedOrderFoodServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderFoodServiceServer struct{}

func (UnimplementedOrderFoodServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedOrderFoodServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedOrderFoodServiceServer) UpdatePasswordUser(context.Context, *UpdatePasswordUserRequest) (*UpdatePasswordUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePasswordUser not implemented")
}
func (UnimplementedOrderFoodServiceServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedOrderFoodServiceServer) mustEmbedUnimplementedOrderFoodServiceServer() {}
func (UnimplementedOrderFoodServiceServer) testEmbeddedByValue()                          {}

// UnsafeOrderFoodServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderFoodServiceServer will
// result in compilation errors.
type UnsafeOrderFoodServiceServer interface {
	mustEmbedUnimplementedOrderFoodServiceServer()
}

func RegisterOrderFoodServiceServer(s grpc.ServiceRegistrar, srv OrderFoodServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrderFoodServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderFoodService_ServiceDesc, srv)
}

func _OrderFoodService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderFoodServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderFoodService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderFoodServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderFoodService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderFoodServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderFoodService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderFoodServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderFoodService_UpdatePasswordUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderFoodServiceServer).UpdatePasswordUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderFoodService_UpdatePasswordUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderFoodServiceServer).UpdatePasswordUser(ctx, req.(*UpdatePasswordUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderFoodService_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderFoodServiceServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderFoodService_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderFoodServiceServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderFoodService_ServiceDesc is the grpc.ServiceDesc for OrderFoodService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderFoodService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderFoodService",
	HandlerType: (*OrderFoodServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _OrderFoodService_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _OrderFoodService_UpdateUser_Handler,
		},
		{
			MethodName: "UpdatePasswordUser",
			Handler:    _OrderFoodService_UpdatePasswordUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _OrderFoodService_LoginUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_order_food.proto",
}
